pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = 'testdocker' // Имя проекта Docker Compose
    }

    stages {
        stage('Checkout') {
            steps {
                // Шаг для клонирования репозитория с GitHub
                git branch: 'master', url: 'https://github.com/losevdmitriy/JenkinsTask.git'
            }
        }
        stage('Build and Start Containers') {
            steps {
                // Шаг для сборки и запуска контейнеров с помощью Docker Compose
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
