pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = 'testdocker' // Имя проекта Docker Compose
    }

    stages {
        stage('Checkout') {
            steps {
                // Шаг для клонирования репозитория с GitHub
                git branch: 'master', url: 'https://github.com/losevdmitriy/JenkinsTask.git'
            }
        }
         stage('Stop Existing Containers') {
                steps {
                   script {
                            sh 'docker-compose down'
                        }
                    }
                }
         stage('Build and Start Containers') {
                    steps {
                        script {
                            sh 'docker-compose up -d --build'
                        }
                    }
                }
    }
}
